#!/system/xbin/busybox sh
busybox=/system/xbin/busybox
$busybox mount -o remount,rw /
$busybox mount -o remount,rw rootfs
$busybox mount -o remount,rw /system

LOG=/system/LOG/boost.log
$busybox clear
$busybox echo ""
$busybox free | $busybox awk '/Mem/{print ">>>...Memory Before Boosting: "$4/1024" MB";}'
$busybox sleep 1
$busybox echo ""
$busybox echo "Dropping cache"
$busybox sync
$busybox sleep 1
$busybox sysctl -w vm.drop_caches=3
$busybox sleep 1
dc=/proc/sys/vm/drop_caches
dc_v=`cat $dc`
if [ "$dc_v" -gt 1 ]; then
$busybox sysctl -w vm.drop_caches=1
fi
$busybox echo ""
$busybox echo ""
$busybox echo "BOOSTED!!!"
$busybox echo ""
$busybox echo ""
$busybox free | $busybox awk '/Mem/{print ">>>...Memory After Boosting : "$4/1024" MB";}'
$busybox echo "RAM boost $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG