#!/system/bin/sh

# force fast charge = 0:disabled, 1:enabled (stock), 2:enabled (custom)
echo "2" >> /sys/kernel/fast_charge/force_fast_charge

# failsafe = 0:disabled, 1:enabled
echo "1" >> /sys/kernel/fast_charge/failsafe

# ac charge levels = 1500, 1600, 1700, 1800, 1900, 2000, 2100,2200,2300,2400,2500,2600,3000,4000,6000
echo "6000" >> /sys/kernel/fast_charge/ac_charge_level

# usb levels =  1000, 1100, 1200,2000,3000,3500,4000
echo "4000" >> /sys/kernel/fast_charge/usb_charge_level

# wireless levels =1000, 1100, 1200,2000,3000
echo "3000" >> /sys/kernel/fast_charge/wireless_charge_level

# display fast charge info
if [ -f /data/fc_info.log ] ; then
   rm /data/fc_info.log
fi
cat /sys/kernel/fast_charge/info >> /data/fc_info.log
echo "
executed on $(date +"%d-%m-%Y %r" )" >> /data/fc_info.log
