#!/system/bin/sh
#ThunderBolt!
#Credit to pikachu01
#Smart Mounting by ImbaWind
#Adrenaline Engine Specified


if ( mount | grep -w ext4 ) then
	echo "EXT4 Partition Found!"
	echo "Remounting..."
	mount -o noatime,remount,rw,discard,barrier=0,commit=60,noauto_da_alloc,delalloc /cache /cache;
	mount -o noatime,remount,rw,discard,barrier=0,commit=60,noauto_da_alloc,delalloc /data /data;
	mount >> /data/adrenaline/engine/etc/fsck.log;
else
	echo "EXT4 Partition Not Found!"
fi;